require "rails/application_controller"

class StaticController < ApplicationController
  layout false #this takes away the CSS generated by rails


  # when I hit this route we dish up react code.
  def index
      render file: Rails.root.join("public", "index.html")
  end
end
